//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst.algorithm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="algorithm.algorithmSoap")]
    public interface algorithmSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 arrayvalues 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrizeLevel", ReplyAction="*")]
        tst.algorithm.PrizeLevelResponse PrizeLevel(tst.algorithm.PrizeLevelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PrizeLevel", ReplyAction="*")]
        System.IAsyncResult BeginPrizeLevel(tst.algorithm.PrizeLevelRequest request, System.AsyncCallback callback, object asyncState);
        
        tst.algorithm.PrizeLevelResponse EndPrizeLevel(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrizeLevelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrizeLevel", Namespace="http://tempuri.org/", Order=0)]
        public tst.algorithm.PrizeLevelRequestBody Body;
        
        public PrizeLevelRequest() {
        }
        
        public PrizeLevelRequest(tst.algorithm.PrizeLevelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrizeLevelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int weight;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arrayvalues;
        
        public PrizeLevelRequestBody() {
        }
        
        public PrizeLevelRequestBody(int weight, string arrayvalues) {
            this.weight = weight;
            this.arrayvalues = arrayvalues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrizeLevelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrizeLevelResponse", Namespace="http://tempuri.org/", Order=0)]
        public tst.algorithm.PrizeLevelResponseBody Body;
        
        public PrizeLevelResponse() {
        }
        
        public PrizeLevelResponse(tst.algorithm.PrizeLevelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrizeLevelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PrizeLevelResult;
        
        public PrizeLevelResponseBody() {
        }
        
        public PrizeLevelResponseBody(int PrizeLevelResult) {
            this.PrizeLevelResult = PrizeLevelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface algorithmSoapChannel : tst.algorithm.algorithmSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrizeLevelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PrizeLevelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class algorithmSoapClient : System.ServiceModel.ClientBase<tst.algorithm.algorithmSoap>, tst.algorithm.algorithmSoap {
        
        private BeginOperationDelegate onBeginPrizeLevelDelegate;
        
        private EndOperationDelegate onEndPrizeLevelDelegate;
        
        private System.Threading.SendOrPostCallback onPrizeLevelCompletedDelegate;
        
        public algorithmSoapClient() {
        }
        
        public algorithmSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public algorithmSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public algorithmSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public algorithmSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<PrizeLevelCompletedEventArgs> PrizeLevelCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        tst.algorithm.PrizeLevelResponse tst.algorithm.algorithmSoap.PrizeLevel(tst.algorithm.PrizeLevelRequest request) {
            return base.Channel.PrizeLevel(request);
        }
        
        public int PrizeLevel(int weight, string arrayvalues) {
            tst.algorithm.PrizeLevelRequest inValue = new tst.algorithm.PrizeLevelRequest();
            inValue.Body = new tst.algorithm.PrizeLevelRequestBody();
            inValue.Body.weight = weight;
            inValue.Body.arrayvalues = arrayvalues;
            tst.algorithm.PrizeLevelResponse retVal = ((tst.algorithm.algorithmSoap)(this)).PrizeLevel(inValue);
            return retVal.Body.PrizeLevelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult tst.algorithm.algorithmSoap.BeginPrizeLevel(tst.algorithm.PrizeLevelRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPrizeLevel(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPrizeLevel(int weight, string arrayvalues, System.AsyncCallback callback, object asyncState) {
            tst.algorithm.PrizeLevelRequest inValue = new tst.algorithm.PrizeLevelRequest();
            inValue.Body = new tst.algorithm.PrizeLevelRequestBody();
            inValue.Body.weight = weight;
            inValue.Body.arrayvalues = arrayvalues;
            return ((tst.algorithm.algorithmSoap)(this)).BeginPrizeLevel(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        tst.algorithm.PrizeLevelResponse tst.algorithm.algorithmSoap.EndPrizeLevel(System.IAsyncResult result) {
            return base.Channel.EndPrizeLevel(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndPrizeLevel(System.IAsyncResult result) {
            tst.algorithm.PrizeLevelResponse retVal = ((tst.algorithm.algorithmSoap)(this)).EndPrizeLevel(result);
            return retVal.Body.PrizeLevelResult;
        }
        
        private System.IAsyncResult OnBeginPrizeLevel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int weight = ((int)(inValues[0]));
            string arrayvalues = ((string)(inValues[1]));
            return this.BeginPrizeLevel(weight, arrayvalues, callback, asyncState);
        }
        
        private object[] OnEndPrizeLevel(System.IAsyncResult result) {
            int retVal = this.EndPrizeLevel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPrizeLevelCompleted(object state) {
            if ((this.PrizeLevelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PrizeLevelCompleted(this, new PrizeLevelCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PrizeLevelAsync(int weight, string arrayvalues) {
            this.PrizeLevelAsync(weight, arrayvalues, null);
        }
        
        public void PrizeLevelAsync(int weight, string arrayvalues, object userState) {
            if ((this.onBeginPrizeLevelDelegate == null)) {
                this.onBeginPrizeLevelDelegate = new BeginOperationDelegate(this.OnBeginPrizeLevel);
            }
            if ((this.onEndPrizeLevelDelegate == null)) {
                this.onEndPrizeLevelDelegate = new EndOperationDelegate(this.OnEndPrizeLevel);
            }
            if ((this.onPrizeLevelCompletedDelegate == null)) {
                this.onPrizeLevelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPrizeLevelCompleted);
            }
            base.InvokeAsync(this.onBeginPrizeLevelDelegate, new object[] {
                        weight,
                        arrayvalues}, this.onEndPrizeLevelDelegate, this.onPrizeLevelCompletedDelegate, userState);
        }
    }
}
